# -*- coding: utf-8 -*-
"""AI Summer SimCLR Resnet18 STL10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhKx8FPwn8GvLbiaOp3m2wZOPZE44tgZ

# SimCLR in STL10 with Resnet18 AI Summer tutorial

## Imports, basic utils, augmentations and Contrastive loss
"""


from torch.multiprocessing import cpu_count


"""## Pretraining main logic"""
from pytorch_lightning import Trainer
from pytorch_lightning import seed_everything
from pytorch_lightning.callbacks import ModelCheckpoint, LearningRateMonitor
from torchvision.models import  resnet18

from dataset import MIMIC_CXR_Dataset
from torch.utils.data import DataLoader
from pytorch_lightning import LightningDataModule

from barlow_twins import BarlowTwins, BarlowTwinsTransform

ROOT = '/home/asim.ukaye/ml_proj/mimic_cxr_pa_resized/'
EPOCHS = 1000
BATCH_SIZE = 64
NUM_WORKERS = 24

CKPT_LOAD = False
CKPT_PATH ='/home/asim.ukaye/ml_proj/simclr_cxr/lightning_logs/version_23/checkpoints/last.ckpt'

seed_everything(1256)


transforms = BarlowTwinsTransform(train=True, input_height=224, jitter_strength=0.5)
train_set = MIMIC_CXR_Dataset(ROOT, split='train',augmentations=transforms)
val_set = MIMIC_CXR_Dataset(ROOT, split='val', augmentations=transforms)

train_loader = DataLoader(train_set, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)
val_loader = DataLoader(val_set, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)

model_pl = BarlowTwins(
    encoder_out_dim=512,
    num_training_samples=len(train_set),
    batch_size=BATCH_SIZE,
    z_dim=128,
)

if CKPT_LOAD:
    model_pl.load_from_checkpoint(CKPT_PATH)


checkpoint_callback = ModelCheckpoint(every_n_epochs=50, save_top_k=-1, save_last=True)

trainer = Trainer(callbacks=[checkpoint_callback, LearningRateMonitor("epoch")], accelerator="auto", devices=1, max_epochs=EPOCHS)


trainer.fit(model_pl, train_loader, val_loader, ckpt_path=CKPT_PATH)
